source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/iFlyCai/IFLYSpecs.git'

use_frameworks!
platform :ios, '16.0'

target 'ZLBaseUI_Example' do
  pod 'ZLBaseUI', :path => '../'

  post_install do |installer|
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.6'
      end
    end
  end
end
